# Generated by Django 2.2.1 on 2019-05-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sjh',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
